### PR TITLE
Plot with cartopy edits (round 2)

### PR DESCRIPTION
**Pull request by pwolfram**
Last round of minor clean up edits

### CODE REVIEW

**Comment by pwolfram** [comment]
@xylar, thanks for all the great work on this.  Please feel free to squash as many of my commits as you would like (or throw them out if you strongly disagree).

**Comment by xylar** [comment]
@pwolfram, I have to say I really don't like either of these changes.  As I said in my previous comments, I know this is an accepted style of python programming but unless there is a requirement for this repository that we follow them, I would rather leave the imports as I had them.

**Comment by xylar** [comment]
My problem is that `ccrs` means nothing to me, whereas `cartopy.crs` gives me a clue about where that's coming from.  I realize I could look at the imports to find that out.  (I also dislike `np` for `numpy` and I would probably use `pyplot` instead of `plt` if that weren't so deeply established.)

**Comment by pwolfram** [comment]
@xylar, sounds good.  Let us abandon the import changes for now and keep an eye on it.  To be consistent we should roll `from os.path import splitext` back to the way you had it (although clearly this is near the line because it has dots three levels deep).  Please see the new changes reflecting this.

**Comment by pwolfram** [comment]
@xylar, I think we should call this done following the changes above (which I think we can agree on) and then I can do the merge at https://github.com/MPAS-Dev/geometric_features/pull/16.  Thanks for helping clarify how we should process imports.

**Pull request merged**
