### PR TITLE
Plot with cartopy edits

### PR DESCRIPTION
**Pull request by pwolfram**
Minor cleanup edits:
- White space fixes
- Update dependency on README
- Clean up module usage

### CODE REVIEW

**Comment by pwolfram** [comment]
@xylar, here are some minor cleanups that I propose for https://github.com/MPAS-Dev/geometric_features/pull/16.

**Comment by xylar** [comment]
@pwolfram, I'm not sure why the os.path --> ospath change was necessary, but I'll leave it.  The rest looks good.  Thanks!

**Comment by pwolfram** [comment]
@xylar, you are right.  I should have done something like

`from os.path import splitext`

The idea here is that if only a few functions (say 3 or less) are used from a module they should be called out to avoid as many long foo.bar.zaz.fiz etc commands in the code to enhance clarity.  I'll make this change because this is better when I do the review.  Thanks for clarifying this lack of precision on my part.  I appreciate it.

**Comment by xylar** [comment]
@pwolfram, I guess there are lots of python programmers that would with your philosophy.  To me, these kinds of imports actually diminish clarity.  I'm somewhere in the middle of the code, nowhere near the imports and I see a function `Polygon`.  How do I know if it's from matplotlib or shapely?  How do I avoid collisions between the two?  I agree that 4 levels of dots is too much but I think having two levels often provides clarity rather than diminishing it, particularly when people do `import x.y as z`.  How am I supposed to know that `z` has anything to do with `x.y`?

If there is going to be a standard practice for this repository that we avoid dots at all cost, I'm willing to abide by it but that wouldn't be my choice.

**Comment by pwolfram** [comment]
@xylar, thanks for clarifying.  I see where you are coming from and mostly agree.  This is what I think we should do: keep an eye on the length of the imports and say that if they grow to be say 4 dots long then revisit this assessment to ensure clarity of the code.  Otherwise, what you propose in terms of imports is fine.  The goal is clarity after all!  I was just trying to follow what I perceived to be standard python practice, although it doesn't appear to be clearly spelled out in the standard (https://www.python.org/dev/peps/pep-0008/).

**Comment by xylar** [comment]
@pwolfram, thanks for pointing out that style guide.  I think you are saying, and I agree, that there doesn't actually seem to be any stated preference between:

```
import mypkg.sibling
from mypkg import sibling
from mypkg.sibling import example
```

Three dots seems like a good cutoff, with a preference for 2 dots or less where possible.

**Comment by pwolfram** [comment]
Agreed

**Pull request merged**
